# Generated by Django 5.1.5 on 2025-04-27 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Acheivements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_spark', models.CharField(default='Completed first study session', max_length=255)),
                ('memory_architect', models.CharField(default='Reviewed card', max_length=255)),
                ('knowledge_engineer', models.CharField(default='Mastered a full deck', max_length=255)),
                ('circuit_complete', models.CharField(default='Finished a study cycle', max_length=255)),
                ('comback_kid', models.CharField(default='Bounced back after missing a review day', max_length=255)),
                ('deck_destroyer', models.CharField(default='Completed 10 decks', max_length=255)),
                ('sage_mode', models.CharField(default='Mastering all cards in a deck', max_length=255)),
                ('midnight_scholar', models.CharField(default='Studied after midnight', max_length=255)),
                ('coffee_powered', models.CharField(default='Ready for a late session', max_length=255)),
                ('underdog_victory', models.CharField(default='Aced a hard deck after multiple failures', max_length=255)),
                ('spark_starter', models.CharField(default='3 Day study streak', max_length=255)),
                ('momentum_builder', models.CharField(default='7 Day study streak', max_length=255)),
                ('unstoppable_force', models.CharField(default='30 Day study streak', max_length=255)),
                ('legend_of_learning', models.CharField(default='100 Day study streak!', max_length=255)),
                ('memory_apprentice', models.CharField(default='Scored 70%+ on recall quiz', max_length=255)),
                ('recall_expert', models.CharField(default='Scored 85%+ on recall quiz', max_length=255)),
                ('recall_champion', models.CharField(default='Scored 95%+ on recall quiz', max_length=255)),
                ('recall_legend', models.CharField(default='maintained 95%+ on recall quizzes for a week', max_length=255)),
                ('deck_explorer', models.CharField(default='Completed 5 decks', max_length=255)),
                ('deck_conqueror', models.CharField(default='Completed 15 decks', max_length=255)),
                ('deck_dominator', models.CharField(default='Completed 30 decks', max_length=255)),
                ('deck_legend', models.CharField(default='Completed 50+ decks', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Badges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brain_builder', models.CharField(default='Added 100+ cards to deck(s)', max_length=255)),
                ('deck_driver', models.CharField(default='Finished a full deck', max_length=255)),
                ('practice_pro', models.CharField(default='Reviewed cards on time 10 times in a row', max_length=255)),
                ('neuron_ninja', models.CharField(default='answered 50 questions correctly in one day', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
