# Generated by Django 5.1.5 on 2025-04-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_alter_acheivements_circuit_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badges',
            name='brain_builder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='badges',
            name='deck_driver',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='badges',
            name='neuron_ninja',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='badges',
            name='practice_pro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
