# Generated by Django 5.1.5 on 2025-04-29 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0004_rename_acheivements_achievements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, unique=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAchievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='badges',
            name='user',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.RemoveField(
            model_name='achievements',
            name='circuit_complete',
        ),
        migrations.RemoveField(
            model_name='achievements',
            name='coffee_powered',
        ),
        migrations.RemoveField(
            model_name='achievements',
            name='comback_kid',
        ),
        migrations.RemoveField(
            model_name='achievements',
            name='deck_conqueror',
        ),
        migrations.RemoveField(
            model_name='achievements',
            name='deck_destroyer',
        ),
        migrations.RemoveField(
            model_name='achievements',
            name='deck_dominator',
        ),
        migrations.RemoveField(
            model_name='achievements',
            name='deck_explorer',
        ),
        migrations.RemoveField(
            model_name='achievements',
            name='deck_legend',
        ),
        migrations.RemoveField(
            model_name='achievements',
            name='first_spark',
        ),
        migrations.RemoveField(
            model_name='achievements',
            name='knowledge_engineer',
        ),
        migrations.RemoveField(
            model_name='achievements',
            name='legend_of_learning',
        ),
        migrations.RemoveField(
            model_name='achievements',
            name='memory_apprentice',
        ),
        migrations.RemoveField(
            model_name='achievements',
            name='memory_architect',
        ),
        migrations.RemoveField(
            model_name='achievements',
            name='midnight_scholar',
        ),
        migrations.RemoveField(
            model_name='achievements',
            name='momentum_builder',
        ),
        migrations.RemoveField(
            model_name='achievements',
            name='recall_champion',
        ),
        migrations.RemoveField(
            model_name='achievements',
            name='recall_expert',
        ),
        migrations.RemoveField(
            model_name='achievements',
            name='recall_legend',
        ),
        migrations.RemoveField(
            model_name='achievements',
            name='sage_mode',
        ),
        migrations.RemoveField(
            model_name='achievements',
            name='spark_starter',
        ),
        migrations.RemoveField(
            model_name='achievements',
            name='underdog_victory',
        ),
        migrations.RemoveField(
            model_name='achievements',
            name='unstoppable_force',
        ),
        migrations.RemoveField(
            model_name='achievements',
            name='user',
        ),
        migrations.AddField(
            model_name='achievements',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='achievements',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='achievements',
            name='tier',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userachievements',
            name='achievements',
            field=models.ManyToManyField(blank=True, to='achievements.achievements'),
        ),
        migrations.AddField(
            model_name='userachievements',
            name='badges',
            field=models.ManyToManyField(blank=True, to='achievements.badge'),
        ),
        migrations.AddField(
            model_name='userachievements',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Badges',
        ),
    ]
