# Generated by Django 5.1.5 on 2025-04-29 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0007_alter_userachievements_achievements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievements',
            name='family',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
