# Generated by Django 5.1.5 on 2025-04-29 00:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_badges_brain_builder_alter_badges_deck_driver_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acheivements',
            new_name='Achievements',
        ),
    ]
