# Generated by Django 5.1.5 on 2025-04-29 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_badge_userachievements_remove_badges_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='tier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userachievements',
            name='achievements',
            field=models.ManyToManyField(null=True, to='dashboard.achievements'),
        ),
        migrations.AlterField(
            model_name='userachievements',
            name='badges',
            field=models.ManyToManyField(null=True, to='dashboard.badge'),
        ),
    ]
