# Generated by Django 5.1.5 on 2025-04-29 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_achievements_tier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userachievements',
            name='achievements',
            field=models.ManyToManyField(to='dashboard.achievements'),
        ),
        migrations.AlterField(
            model_name='userachievements',
            name='badges',
            field=models.ManyToManyField(to='dashboard.badge'),
        ),
    ]
