# Generated by Django 4.2.21 on 2026-05-25 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UPSUserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('neuro_response', models.TextField()),
                ('explanation', models.TextField(blank=True, null=True)),
                ('principles', models.JSONField(blank=True, default=list, null=True)),
                ('solution_summary', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DFBLUserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neuro_response', models.TextField(blank=True, null=True)),
                ('user_answer', models.TextField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('layer', models.IntegerField(default=1)),
                ('tutor_style', models.CharField(choices=[('strict', 'Strict'), ('friendly', 'Friendly'), ('professional', 'Professional'), ('speed_run', 'Speed run'), ('socratic', 'Socratic'), ('supportive', 'Supportive')], default='socratic', max_length=255)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('principles', models.JSONField(blank=True, default=list, null=True)),
                ('solution_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flashcards.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
