# Generated by Django 4.2.21 on 2025-12-31 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claude_client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dfbluserinteraction',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dfbluserinteraction',
            name='user_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dfbluserinteraction',
            name='neuro_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
