# Generated by Django 4.2.21 on 2025-10-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claude_client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='user_answer',
            field=models.JSONField(default=list),
        ),
    ]
