# Generated by Django 4.2.21 on 2026-01-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claude_client', '0002_dfbluserinteraction_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dfbluserinteraction',
            name='layer',
            field=models.IntegerField(default=1),
        ),
    ]
