# Generated by Django 4.2.21 on 2025-10-20 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('claude_client', '0002_alter_question_user_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neuro_response', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DFBLUserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('attempts', models.IntegerField()),
                ('correct_answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studymethod', models.CharField(choices=[('dfbl', 'Doing + Feedback Loop')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='studymethod',
        ),
        migrations.DeleteModel(
            name='DoingFeedbackLoop',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='dfbluserinteraction',
            name='dfbl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dfbl', to='claude_client.studysession'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user_interaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claude_client.dfbluserinteraction'),
        ),
    ]
