# Generated by Django 4.2.21 on 2025-10-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claude_client', '0003_conversation_dfbluserinteraction_studysession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysession',
            name='studymethod',
            field=models.CharField(choices=[('dfbl', 'Doing + Feedback Loop'), ('rr', 'Recall + Retention'), ('ups', 'Understanding + Problem Solving'), ('pral', 'Pattern Recognition + Applied Learning')], max_length=4),
        ),
    ]
