# Generated by Django 4.2.21 on 2025-10-20 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claude_client', '0004_alter_studysession_studymethod'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conversation',
            new_name='ConversationHistory',
        ),
    ]
