# Generated by Django 4.2.21 on 2025-10-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claude_client', '0005_rename_conversation_conversationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='dfbluserinteraction',
            name='user_answer',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
