# Generated by Django 4.2.21 on 2025-10-20 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('claude_client', '0006_dfbluserinteraction_user_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studysession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dfbluserinteraction',
            name='dfbl',
        ),
        migrations.AddField(
            model_name='dfbluserinteraction',
            name='neuro_response',
            field=models.TextField(default='You so stupid'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dfbluserinteraction',
            name='studymethod',
            field=models.TextField(default='dfbl'),
        ),
        migrations.AddField(
            model_name='dfbluserinteraction',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ConversationHistory',
        ),
        migrations.DeleteModel(
            name='StudySession',
        ),
    ]
