# Generated by Django 4.2.21 on 2025-10-27 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('claude_client', '0007_remove_studysession_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UPSUserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principles', models.TextField()),
                ('solution_summary', models.TextField()),
                ('neuro_response', models.TextField()),
                ('question', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
