# Generated by Django 4.2.21 on 2025-10-27 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claude_client', '0008_upsuserinteraction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dfbluserinteraction',
            name='studymethod',
        ),
    ]
