# Generated by Django 4.2.21 on 2025-10-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claude_client', '0009_remove_dfbluserinteraction_studymethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='upsuserinteraction',
            name='explanation',
            field=models.TextField(default='stock'),
            preserve_default=False,
        ),
    ]
