# Generated by Django 4.2.21 on 2025-10-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claude_client', '0010_upsuserinteraction_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upsuserinteraction',
            name='principles',
            field=models.JSONField(default=list),
        ),
    ]
