# Generated by Django 4.2.21 on 2025-10-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claude_client', '0011_alter_upsuserinteraction_principles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upsuserinteraction',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='upsuserinteraction',
            name='solution_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
