# Generated by Django 4.2.21 on 2025-10-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claude_client', '0012_alter_upsuserinteraction_explanation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upsuserinteraction',
            name='principles',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
