# Generated by Django 4.2.21 on 2025-11-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claude_client', '0013_alter_upsuserinteraction_principles'),
    ]

    operations = [
        migrations.AddField(
            model_name='upsuserinteraction',
            name='tutor_style',
            field=models.CharField(choices=[('strict', 'Strict'), ('friendly', 'Friendly'), ('professional', 'Professional'), ('speed_run', 'Speed run'), ('socratic', 'Socratic'), ('supportive', 'Supportive')], default='socratic', max_length=255),
        ),
    ]
