# Generated by Django 4.2.21 on 2025-11-15 10:59

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0012_remove_card_layer'),
        ('claude_client', '0014_upsuserinteraction_tutor_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upsuserinteraction',
            name='question',
        ),
        migrations.AddField(
            model_name='upsuserinteraction',
            name='card',
            field=models.ForeignKey(default='283', on_delete=django.db.models.deletion.CASCADE, to='flashcards.card'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upsuserinteraction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
    ]
