# Generated by Django 4.2.21 on 2025-11-15 11:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0012_remove_card_layer'),
        ('claude_client', '0015_remove_upsuserinteraction_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dfbluserinteraction',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='dfbluserinteraction',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='dfbluserinteraction',
            name='question',
        ),
        migrations.RemoveField(
            model_name='dfbluserinteraction',
            name='user_answer',
        ),
        migrations.RemoveField(
            model_name='upsuserinteraction',
            name='card',
        ),
        migrations.RemoveField(
            model_name='upsuserinteraction',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='upsuserinteraction',
            name='tutor_style',
        ),
        migrations.AddField(
            model_name='dfbluserinteraction',
            name='card',
            field=models.ForeignKey(default='283', on_delete=django.db.models.deletion.CASCADE, to='flashcards.card'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dfbluserinteraction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dfbluserinteraction',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dfbluserinteraction',
            name='principles',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='dfbluserinteraction',
            name='solution_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dfbluserinteraction',
            name='tutor_style',
            field=models.CharField(choices=[('strict', 'Strict'), ('friendly', 'Friendly'), ('professional', 'Professional'), ('speed_run', 'Speed run'), ('socratic', 'Socratic'), ('supportive', 'Supportive')], default='socratic', max_length=255),
        ),
        migrations.AddField(
            model_name='upsuserinteraction',
            name='question',
            field=models.TextField(default='Random Question'),
            preserve_default=False,
        ),
    ]
