# Generated by Django 4.2.21 on 2025-08-16 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0025_remove_fileupload_file_pinned_and_more'),
        ('documents', '0012_remove_document_document_pinned'),
        ('solostudyroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinnedresources',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.document'),
        ),
        migrations.AddField(
            model_name='pinnedresources',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.fileupload'),
        ),
        migrations.AddField(
            model_name='pinnedresources',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.linkupload'),
        ),
    ]
