# Generated by Django 4.2.21 on 2025-08-17 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solostudyroom', '0002_pinnedresources_document_pinnedresources_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pinnedresources',
            old_name='document',
            new_name='pinned_document',
        ),
        migrations.RenameField(
            model_name='pinnedresources',
            old_name='file',
            new_name='pinned_file',
        ),
        migrations.RenameField(
            model_name='pinnedresources',
            old_name='link',
            new_name='pinned_link',
        ),
    ]
