# Generated by Django 4.2.21 on 2026-05-23 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solostudyroom', '0002_avgcardstudiedweekly'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvgCardStudiedWeekly',
        ),
    ]
