# Generated by Django 4.2.21 on 2025-08-17 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solostudyroom', '0003_rename_document_pinnedresources_pinned_document_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pinnedresources',
            old_name='pinned_document',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='pinnedresources',
            old_name='pinned_file',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='pinnedresources',
            old_name='pinned_link',
            new_name='link',
        ),
    ]
