# Generated by Django 4.2.21 on 2025-08-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0025_remove_fileupload_file_pinned_and_more'),
        ('documents', '0013_document_resource_type_document_tag_delete_tag'),
        ('solostudyroom', '0004_rename_pinned_document_pinnedresources_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pinnedresources',
            name='document',
        ),
        migrations.RemoveField(
            model_name='pinnedresources',
            name='file',
        ),
        migrations.RemoveField(
            model_name='pinnedresources',
            name='link',
        ),
        migrations.AddField(
            model_name='pinnedresources',
            name='document',
            field=models.ManyToManyField(blank=True, null=True, to='documents.document'),
        ),
        migrations.AddField(
            model_name='pinnedresources',
            name='file',
            field=models.ManyToManyField(blank=True, null=True, to='resources.fileupload'),
        ),
        migrations.AddField(
            model_name='pinnedresources',
            name='link',
            field=models.ManyToManyField(blank=True, null=True, to='resources.linkupload'),
        ),
    ]
