# Generated by Django 4.2.21 on 2025-08-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_document_resource_type_document_tag_delete_tag'),
        ('resources', '0025_remove_fileupload_file_pinned_and_more'),
        ('solostudyroom', '0005_remove_pinnedresources_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinnedresources',
            name='document',
            field=models.ManyToManyField(blank=True, to='documents.document'),
        ),
        migrations.AlterField(
            model_name='pinnedresources',
            name='file',
            field=models.ManyToManyField(blank=True, to='resources.fileupload'),
        ),
        migrations.AlterField(
            model_name='pinnedresources',
            name='link',
            field=models.ManyToManyField(blank=True, to='resources.linkupload'),
        ),
    ]
