# Generated by Django 4.2.21 on 2025-08-20 02:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0025_remove_fileupload_file_pinned_and_more'),
        ('documents', '0013_document_resource_type_document_tag_delete_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solostudyroom', '0006_alter_pinnedresources_document_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PinnedResources',
            new_name='PinnedResourcesDashboard',
        ),
    ]
