# Generated by Django 6.0.8 on 2026-08-10 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('folders', '0001_initial'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled', max_length=255)),
                ('notes', models.TextField()),
                ('saved', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(default=False)),
                ('resource_type', models.CharField(default='Document', max_length=8)),
                ('tag', models.CharField(blank=True, max_length=255, null=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_document', to='folders.folder')),
                ('pr_dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.pinnedresourcesdashboard')),
            ],
        ),
    ]
