# Generated by Django 4.2.21 on 2025-08-29 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('folders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled', max_length=255)),
                ('notes', models.TextField()),
                ('saved', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(default=False)),
                ('resource_type', models.CharField(choices=[('document', 'Document')], max_length=8)),
                ('tag', models.CharField(blank=True, max_length=255, null=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='folders.folder')),
            ],
        ),
    ]
