# Generated by Django 4.2.21 on 2025-06-06 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0003_folder_content_num'),
        ('documents', '0002_alter_document_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='folders.folder'),
        ),
    ]
