# Generated by Django 4.2.21 on 2025-07-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
