# Generated by Django 4.2.21 on 2025-07-22 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_published_document_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='created_at',
            new_name='saved',
        ),
    ]
