# Generated by Django 4.2.21 on 2025-08-14 00:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('solostudyroom', '0001_initial'),
        ('documents', '0007_tag_delete_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pinned_resource',
            field=models.ForeignKey(null=True, default=None, blank=True, on_delete=django.db.models.deletion.CASCADE, to='solostudyroom.pinnedresources'),
            preserve_default=False,
        ),
    ]
