# Generated by Django 4.2.21 on 2025-08-14 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_document_pinned_resource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='pinned_resource',
            new_name='document_pinned',
        ),
    ]
