# Generated by Django 4.2.21 on 2025-08-14 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solostudyroom', '0001_initial'),
        ('documents', '0010_alter_document_document_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_pinned',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='solostudyroom.pinnedresources'),
        ),
    ]
