# Generated by Django 4.2.21 on 2025-08-16 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_alter_document_document_pinned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document_pinned',
        ),
    ]
