# Generated by Django 4.2.21 on 2025-08-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_remove_document_document_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='resource_type',
            field=models.CharField(choices=[('document', 'Document')], default='document', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
