# Generated by Django 4.2.21 on 2025-12-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='google_access_token',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='google_refresh_token',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='jwt_token',
            field=models.CharField(null=True),
        ),
    ]
