# Generated by Django 4.2.21 on 2026-05-25 23:16

import authentication.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', authentication.models.CustomManager()),
            ],
        ),
    ]
