# Generated by Django 4.2.21 on 2025-11-04 16:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='current_streak',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='authuser',
            name='longest_streak',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
