# Generated by Django 5.1.5 on 2025-04-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
