# Generated by Django 4.2.21 on 2025-11-26 22:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_authuser_current_streak_authuser_longest_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='last_login_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='current_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='longest_streak',
            field=models.IntegerField(default=0),
        ),
    ]
