# Generated by Django 4.2.21 on 2026-06-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='google_access_token',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='google_refresh_token',
            field=models.CharField(null=True),
        ),
    ]
