# Generated by Django 4.2.21 on 2025-11-07 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_authuser_last_login_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='current_streak',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='last_login_date',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='longest_streak',
        ),
    ]
