# Generated by Django 5.1.5 on 2025-04-18 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_authuser_groups_authuser_user_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='access_token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='authuser',
            name='expires_in',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
