# Generated by Django 5.1.5 on 2025-04-18 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_authuser_access_token_authuser_expires_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='refresh_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
