# Generated by Django 4.2.21 on 2026-06-13 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_access_token_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='google_refresh_token',
        ),
    ]
