# Generated by Django 4.2.21 on 2025-12-31 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_authuser_google_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='google_access_token',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='google_refresh_token',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='jwt_token',
            field=models.CharField(null=True),
        ),
    ]
