# Generated by Django 5.1.5 on 2025-04-18 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_authuser_refresh_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='expires_in',
        ),
        migrations.AddField(
            model_name='authuser',
            name='access_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
