# Generated by Django 6.0.6 on 2026-07-07 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_user_google_refresh_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='access_token_expires_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='google_access_token',
        ),
    ]
