# Generated by Django 4.2.21 on 2026-05-23 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_authuser_google_access_token_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthUser',
        ),
    ]
