# Generated by Django 5.1.5 on 2025-04-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_authuser_expires_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
