# Generated by Django 5.1.5 on 2025-04-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_authuser_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
