# Generated by Django 5.1.5 on 2025-05-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_authuser_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='plan',
            field=models.CharField(default='Free plan', max_length=255),
        ),
    ]
