# Generated by Django 5.1.5 on 2025-05-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_authuser_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='plan',
            field=models.CharField(default='Free Tier', max_length=255),
        ),
    ]
