# Generated by Django 5.1.5 on 2025-05-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_authuser_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='token_amount',
            field=models.IntegerField(default=1000),
        ),
    ]
