# Generated by Django 5.1.5 on 2025-05-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_authuser_token_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='plan',
            field=models.CharField(default='Note Taker', max_length=255),
        ),
    ]
