# Generated by Django 4.2.21 on 2025-05-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_authuser_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='app_refresh_token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='authuser',
            name='app_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
