# Generated by Django 4.2.21 on 2025-05-18 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_authuser_app_refresh_token_authuser_app_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authuser',
            old_name='app_refresh_token',
            new_name='jwt_token',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='app_token',
        ),
    ]
