# Generated by Django 4.2.21 on 2025-06-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_rename_app_refresh_token_authuser_jwt_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='authuser',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
