# Generated by Django 4.2.21 on 2025-07-04 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_authuser_level_authuser_xp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authuser',
            old_name='access_token',
            new_name='google_access_token',
        ),
        migrations.RenameField(
            model_name='authuser',
            old_name='refresh_token',
            new_name='google_refresh_token',
        ),
    ]
