# Generated by Django 4.2.21 on 2025-07-04 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_rename_access_token_authuser_google_access_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='timezone',
        ),
    ]
