# Generated by Django 4.2.21 on 2025-11-28 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('learning_status', models.CharField(choices=[('unseen', 'Unseen'), ('strgl', 'struggling'), ('imprv', 'Improving'), ('mstrd', 'Mastered')], default='unseen', max_length=10)),
                ('repetitions', models.IntegerField(default=0)),
                ('difficulty', models.FloatField(default=5.0)),
                ('stability', models.FloatField(default=1440.0)),
                ('last_review_date', models.DateTimeField(blank=True, null=True)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_time', models.DurationField()),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('cards', models.ManyToManyField(related_name='reviewed_cards', to='flashcards.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_review_log', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('subject', models.CharField(default='No subject provided', max_length=255)),
                ('num_of_cards', models.IntegerField(default=0)),
                ('mastery_progress', models.FloatField(default=0)),
                ('is_mastered', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='card_deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_deck', to='flashcards.deck'),
        ),
    ]
