# Generated by Django 6.0.8 on 2026-08-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='card',
            name='learning_status',
        ),
        migrations.RemoveField(
            model_name='card',
            name='scheduled_date',
        ),
        migrations.RemoveField(
            model_name='card',
            name='stability',
        ),
        migrations.RemoveField(
            model_name='card',
            name='todays_review_count',
        ),
        migrations.AddField(
            model_name='card',
            name='bucket',
            field=models.CharField(choices=[('bkt_0', 'New Card'), ('bkt_1', 'Bucket 1'), ('bkt_2', 'Bucket 2'), ('bkt_3', 'Bucket 3'), ('bkt_4', 'Bucket 4')], default='bkt_0'),
        ),
        migrations.AlterField(
            model_name='card',
            name='last_review_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
