# Generated by Django 4.2.21 on 2025-09-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewlog',
            name='session_time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='reviewlog',
            name='card',
        ),
        migrations.AddField(
            model_name='reviewlog',
            name='card',
            field=models.ManyToManyField(related_name='reviewed_cards', to='flashcards.card'),
        ),
    ]
