# Generated by Django 4.2.21 on 2025-09-08 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flashcards', '0002_reviewlog_session_time_remove_reviewlog_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewlog',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_review_log', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
