# Generated by Django 4.2.21 on 2026-02-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_doingfeedbackreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doingfeedbackreview',
            name='layer_one_explanation',
        ),
        migrations.RemoveField(
            model_name='doingfeedbackreview',
            name='layer_three_explanation',
        ),
        migrations.RemoveField(
            model_name='doingfeedbackreview',
            name='layer_two_explanation',
        ),
        migrations.AddField(
            model_name='doingfeedbackreview',
            name='dfbl_attempt_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='doingfeedbackreview',
            name='layer_one_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doingfeedbackreview',
            name='layer_three_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doingfeedbackreview',
            name='layer_two_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
