# Generated by Django 5.1.5 on 2025-04-19 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_deck_user_deck'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='user_deck',
            new_name='user',
        ),
    ]
