# Generated by Django 5.1.5 on 2025-04-21 00:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_rename_user_deck_deck_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='due_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='card',
            name='ease_factor',
            field=models.IntegerField(default=2.5),
        ),
        migrations.AddField(
            model_name='card',
            name='interval',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='card',
            name='last_reviewed',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='card',
            name='repitions',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='deck',
            name='subject',
            field=models.CharField(default='No subject provided', max_length=255),
        ),
    ]
