# Generated by Django 4.2.21 on 2025-09-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_reviewlog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewlog',
            name='session_time',
            field=models.DurationField(),
        ),
    ]
