# Generated by Django 4.2.21 on 2026-04-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_remove_doingfeedbackreview_layer_one_explanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='todays_review_count',
            field=models.JSONField(default=dict),
        ),
    ]
