# Generated by Django 5.1.5 on 2025-04-27 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_card_due_date_card_ease_factor_card_interval_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='card',
            name='ease_factor',
        ),
        migrations.RemoveField(
            model_name='card',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='card',
            name='last_reviewed',
        ),
        migrations.RemoveField(
            model_name='card',
            name='repitions',
        ),
        migrations.AddField(
            model_name='card',
            name='difficulty',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='card',
            name='last_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='repetitions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='stability',
            field=models.FloatField(default=1.0),
        ),
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField()),
                ('stability', models.FloatField()),
                ('difficulty', models.FloatField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcards.card')),
            ],
        ),
    ]
