# Generated by Django 4.2.21 on 2025-09-08 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_alter_reviewlog_session_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewlog',
            old_name='card',
            new_name='cards',
        ),
    ]
