# Generated by Django 4.2.21 on 2025-09-09 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_rename_card_reviewlog_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewlog',
            name='reviewed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
