# Generated by Django 5.1.5 on 2025-04-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_remove_card_due_date_remove_card_ease_factor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewlog',
            name='reviewed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
