# Generated by Django 5.1.5 on 2025-04-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0006_alter_reviewlog_reviewed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewlog',
            name='reviewed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
