# Generated by Django 4.2.21 on 2025-09-12 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0006_reviewlog_reviewed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_progress_status',
            field=models.CharField(choices=[('strgl', 'struggling'), ('imprv', 'Improving'), ('mstrd', 'Mastered')], default='imprv', max_length=10),
        ),
        migrations.AddField(
            model_name='deck',
            name='is_mastered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deck',
            name='mastery_progress',
            field=models.IntegerField(default=0),
        ),
    ]
