# Generated by Django 4.2.21 on 2025-09-12 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0007_card_card_progress_status_deck_is_mastered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='card_progress_status',
        ),
        migrations.AlterField(
            model_name='card',
            name='learning_status',
            field=models.CharField(choices=[('unseen', 'Unseen'), ('strgl', 'struggling'), ('imprv', 'Improving'), ('mstrd', 'Mastered')], default='unseen', max_length=10),
        ),
    ]
