# Generated by Django 5.1.5 on 2025-04-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0007_alter_reviewlog_reviewed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='correct',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='incorrect',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
