# Generated by Django 5.1.5 on 2025-04-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0008_card_correct_card_incorrect'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewlog',
            name='scheduled_review',
            field=models.DateField(null=True),
        ),
    ]
