# Generated by Django 4.2.21 on 2025-09-12 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0008_remove_card_card_progress_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_deck', to='flashcards.deck'),
        ),
    ]
