# Generated by Django 4.2.21 on 2025-09-12 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0009_alter_card_card_deck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='mastery_progress',
            field=models.FloatField(default=0),
        ),
    ]
