# Generated by Django 5.1.5 on 2025-05-05 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0009_reviewlog_scheduled_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewlog',
            name='scheduled_review',
        ),
    ]
