# Generated by Django 4.2.21 on 2025-11-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0010_alter_deck_mastery_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='layer',
            field=models.IntegerField(default=1),
        ),
    ]
