# Generated by Django 5.1.5 on 2025-05-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0010_remove_reviewlog_scheduled_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='overdue',
            field=models.DateField(null=True),
        ),
    ]
