# Generated by Django 4.2.21 on 2025-11-15 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0011_card_layer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='layer',
        ),
    ]
