# Generated by Django 5.1.5 on 2025-05-05 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0011_card_overdue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='overdue',
        ),
    ]
