# Generated by Django 5.1.5 on 2025-05-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0012_remove_card_overdue'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_overdue',
            field=models.BooleanField(default=False),
        ),
    ]
