# Generated by Django 4.2.21 on 2025-05-26 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0001_initial'),
        ('flashcards', '0013_card_is_overdue'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='folders.folder'),
        ),
    ]
