# Generated by Django 4.2.21 on 2025-05-29 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0014_deck_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='folder',
        ),
    ]
