# Generated by Django 4.2.21 on 2025-05-30 22:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0002_folder_user_alter_folder_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flashcards', '0015_remove_deck_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='deck',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='folders.folder'),
        ),
        migrations.AddField(
            model_name='deck',
            name='last_studied',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='UserStudyPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_goal', models.IntegerField(default=20)),
                ('reminder_time', models.TimeField(blank=True, null=True)),
                ('reminder_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('none', 'None')], default='none', max_length=10)),
                ('reminder_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('study_reminder_enabled', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudyStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_study_date', models.DateField(null=True)),
                ('total_cards_reviewed', models.IntegerField(default=0)),
                ('total_study_days', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('notification_type', models.CharField(choices=[('reminder', 'Study Reminder'), ('streak', 'Streak Milestone'), ('overdue', 'Overdue Cards'), ('achievement', 'Achievement')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyStudyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('cards_reviewed', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('study_time_minutes', models.IntegerField(default=0)),
                ('decks_studied', models.ManyToManyField(to='flashcards.deck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
