# Generated by Django 4.2.21 on 2025-05-31 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0016_deck_created_at_deck_folder_deck_last_studied_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studystreak',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userstudypreferences',
            name='user',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='last_studied',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='reviewlog',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='reviewlog',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='reviewlog',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='reviewlog',
            name='stability',
        ),
        migrations.DeleteModel(
            name='DailyStudyLog',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='StudyStreak',
        ),
        migrations.DeleteModel(
            name='UserStudyPreferences',
        ),
    ]
