# Generated by Django 4.2.21 on 2025-05-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0017_remove_notification_user_remove_studystreak_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewlog',
            name='cards_reviewd',
            field=models.IntegerField(default=0),
        ),
    ]
