# Generated by Django 4.2.21 on 2025-05-31 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0018_reviewlog_cards_reviewd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewlog',
            old_name='cards_reviewd',
            new_name='cards_reviewed',
        ),
    ]
