# Generated by Django 4.2.21 on 2025-05-31 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0019_rename_cards_reviewd_reviewlog_cards_reviewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewlog',
            name='cards_reviewed',
        ),
        migrations.AddField(
            model_name='reviewlog',
            name='reviewed_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
