# Generated by Django 4.2.21 on 2025-05-31 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0020_remove_reviewlog_cards_reviewed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewlog',
            name='reviewed_at',
        ),
    ]
