# Generated by Django 4.2.21 on 2025-06-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0021_remove_reviewlog_reviewed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='num_of_cards',
            field=models.IntegerField(default=0),
        ),
    ]
