# Generated by Django 4.2.21 on 2025-06-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0022_deck_num_of_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='learning_status',
            field=models.CharField(default='In progress', max_length=255),
        ),
    ]
