# Generated by Django 4.2.21 on 2025-06-18 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0023_card_learning_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='correct',
        ),
        migrations.RemoveField(
            model_name='card',
            name='incorrect',
        ),
        migrations.RemoveField(
            model_name='card',
            name='is_overdue',
        ),
    ]
