# Generated by Django 4.2.21 on 2025-06-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0024_remove_card_correct_remove_card_incorrect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='learning_status',
            field=models.CharField(default='Unseen', max_length=255),
        ),
    ]
