# Generated by Django 4.2.21 on 2025-07-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0025_alter_card_learning_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='last_review_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
