# Generated by Django 4.2.21 on 2025-07-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0026_alter_card_last_review_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='stability',
            field=models.FloatField(default=1440.0),
        ),
    ]
