# Generated by Django 4.2.21 on 2025-06-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0002_folder_user_alter_folder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='content_num',
            field=models.IntegerField(default=0),
        ),
    ]
