# Generated by Django 4.2.21 on 2025-09-14 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0002_subfolder_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_folders', to='folders.folder'),
        ),
        migrations.DeleteModel(
            name='SubFolder',
        ),
    ]
