# Generated by Django 4.2.21 on 2025-09-14 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0003_folder_parent_delete_subfolder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='parent',
            new_name='sub_folder',
        ),
    ]
