# Generated by Django 4.2.21 on 2025-09-14 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0004_rename_parent_folder_sub_folder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='sub_folder',
            new_name='parent_folder',
        ),
    ]
