# Generated by Django 4.2.21 on 2025-06-25 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0004_subfolder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subfolder',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_folders', to='folders.folder'),
        ),
    ]
