# Generated by Django 4.2.21 on 2026-02-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_alter_question_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time_taken',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='time_taken',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
