# Generated by Django 4.2.21 on 2026-02-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_question_time_taken_quizattempt_time_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
