# Generated by Django 4.2.21 on 2025-05-27 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_question_question_type_alter_question_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(default='No quiz provided', on_delete=django.db.models.deletion.CASCADE, to='tests.quiz'),
        ),
    ]
