# Generated by Django 4.2.21 on 2025-05-27 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_alter_answer_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MC', 'Multiple Choice'), ('WR', 'Written')], default='MC', max_length=2),
        ),
    ]
