# Generated by Django 4.2.21 on 2025-05-28 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0002_folder_user_alter_folder_name'),
        ('tests', '0009_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='folders.folder'),
        ),
    ]
