# Generated by Django 4.2.21 on 2025-06-06 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0003_folder_content_num'),
        ('tests', '0010_quiz_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='folders.folder'),
        ),
    ]
