# Generated by Django 4.2.21 on 2025-06-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_quizattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='topic',
            field=models.CharField(default='Untitled', max_length=255, null=True),
        ),
    ]
