# Generated by Django 4.2.21 on 2025-06-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0015_cardstoquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_cards_to_quiz',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='CardsToQuiz',
        ),
    ]
