# Generated by Django 4.2.21 on 2026-06-03 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neuro_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neuroprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='neuroprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
