# Generated by Django 4.2.21 on 2026-06-12 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        ('documents', '0001_initial'),
        ('neuro_profile', '0002_remove_neuroprofile_id_alter_neuroprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinnedResourcesDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ManyToManyField(blank=True, to='documents.document')),
                ('file', models.ManyToManyField(blank=True, to='resources.fileupload')),
                ('link', models.ManyToManyField(blank=True, to='resources.linkupload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neuro_profile.neuroprofile')),
            ],
        ),
    ]
