# Generated by Django 4.2.21 on 2026-06-12 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neuro_profile', '0003_pinnedresourcesdashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinnedresourcesdashboard',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='neuro_profile.neuroprofile'),
        ),
    ]
