# Generated by Django 4.2.21 on 2026-06-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuro_profile', '0004_alter_pinnedresourcesdashboard_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='neuroprofile',
            name='jwt_refresh',
            field=models.CharField(null=True),
        ),
    ]
