# Generated by Django 4.2.21 on 2026-06-13 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neuro_profile', '0005_neuroprofile_jwt_refresh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neuroprofile',
            name='jwt_refresh',
        ),
    ]
