# Generated by Django 6.0.6 on 2026-07-07 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neuro_profile', '0006_remove_neuroprofile_jwt_refresh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neuroprofile',
            name='jwt_token',
        ),
    ]
