# Generated by Django 6.0.6 on 2026-08-10 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neuro_profile', '0007_remove_neuroprofile_jwt_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PinnedResourcesDashboard',
        ),
    ]
