# Generated by Django 4.2.21 on 2025-07-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(choices=[('link', 'Link'), ('pdf', 'PDF'), ('textbook', 'Textbook')], max_length=255, upload_to={('upload_textbook', 'Textbook'), ('upload_pdf', 'PDF'), ('upload_link', 'Link')})),
                ('uploaded_at', models.DateTimeField()),
            ],
        ),
    ]
