# Generated by Django 6.0.8 on 2026-08-10 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('neuro_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinnedResourcesDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='neuro_profile.neuroprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PDFUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('resource_type', models.CharField(default='PDF', max_length=8)),
                ('object_name', models.CharField(max_length=255)),
                ('pr_dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.pinnedresourcesdashboard')),
            ],
        ),
        migrations.CreateModel(
            name='LinkUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('resource_type', models.CharField(default='Link', max_length=8)),
                ('pr_dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.pinnedresourcesdashboard')),
            ],
        ),
    ]
