# Generated by Django 6.0.6 on 2026-08-10 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('neuro_profile', '0008_delete_pinnedresourcesdashboard'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinnedResourcesDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ManyToManyField(blank=True, to='documents.document')),
                ('file', models.ManyToManyField(blank=True, to='resources.fileupload')),
                ('link', models.ManyToManyField(blank=True, to='resources.linkupload')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='neuro_profile.neuroprofile')),
            ],
        ),
    ]
