# Generated by Django 4.2.21 on 2025-07-31 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileTypes',
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(choices=[('textbook', 'Textbook'), ('pdf', 'PDF'), ('link', 'Link')], max_length=255, upload_to=[('textbook', 'Textbook'), ('pdf', 'PDF'), ('link', 'Link')]),
        ),
    ]
