# Generated by Django 4.2.21 on 2025-07-31 20:04

from django.db import migrations, models
import resources.models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_delete_filetypes_alter_resource_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='file',
        ),
        migrations.AddField(
            model_name='resource',
            name='file_type',
            field=models.CharField(choices=[('textbook', 'Textbook'), ('pdf', 'PDF'), ('link', 'Link')], default='PDF', max_length=8),
        ),
        migrations.AddField(
            model_name='resource',
            name='file_upload',
            field=models.FileField(default='defaults/defaultuser/default.pdf', upload_to=resources.models.Resource.user_directory_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
