# Generated by Django 4.2.21 on 2025-07-31 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_resource_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='filename',
            field=models.CharField(default='Untitled', max_length=255),
        ),
    ]
