# Generated by Django 4.2.21 on 2025-07-31 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_resource_filename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='filename',
            new_name='file_name',
        ),
    ]
