# Generated by Django 4.2.21 on 2025-08-01 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_rename_filename_resource_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='file_type',
        ),
    ]
