# Generated by Django 4.2.21 on 2025-08-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_remove_resource_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=255)),
            ],
        ),
    ]
