# Generated by Django 4.2.21 on 2025-08-11 14:35

from django.db import migrations, models
import django.db.models.deletion
import resources.models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_linkmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_upload', models.FileField(upload_to=resources.models.FileUpload.user_directory_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(default='Untitled', max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='LinkModel',
            new_name='LinkUpload',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='file_upload',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='resource',
            name='link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.linkupload'),
        ),
        migrations.AddField(
            model_name='resource',
            name='file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resources.fileupload'),
            preserve_default=False,
        ),
    ]
