# Generated by Django 4.2.21 on 2025-08-11 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_alter_resource_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_resource', to='resources.fileupload'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_resource', to='resources.linkupload'),
        ),
    ]
