# Generated by Django 4.2.21 on 2025-08-11 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0013_remove_resource_file_remove_resource_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='linkupload',
            name='resource',
        ),
        migrations.AddField(
            model_name='resource',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_resource', to='resources.fileupload'),
        ),
        migrations.AddField(
            model_name='resource',
            name='link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='link_resource', to='resources.linkupload'),
        ),
    ]
