# Generated by Django 4.2.21 on 2025-08-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0015_remove_resource_file_remove_resource_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='file_type',
            field=models.CharField(default='pdf', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linkupload',
            name='title',
            field=models.CharField(default='Calc Lecture', max_length=255),
            preserve_default=False,
        ),
    ]
