# Generated by Django 4.2.21 on 2025-08-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0016_fileupload_file_type_linkupload_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(default='textbook', max_length=8),
            preserve_default=False,
        ),
    ]
