# Generated by Django 4.2.21 on 2025-08-11 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0017_resource_resource_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='file_type',
        ),
    ]
