# Generated by Django 4.2.21 on 2025-08-12 04:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0018_remove_fileupload_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkupload',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
