# Generated by Django 4.2.21 on 2025-08-12 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0019_linkupload_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='linkupload',
            name='resource',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='file_type',
            field=models.CharField(choices=[('epub', 'EPUB'), ('mobi', 'MOBI'), ('azw3', 'AZW3'), ('docx', 'DOCX'), ('pdf', 'PDF')], default='PDF', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileupload',
            name='resource_type',
            field=models.CharField(choices=[('textbook', 'Textbook'), ('pdf', 'PDF'), ('link', 'Link')], default='PDF', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linkupload',
            name='resource_type',
            field=models.CharField(default='link', max_length=8),
        ),
        migrations.AddField(
            model_name='linkupload',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='link_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
