# Generated by Django 4.2.21 on 2025-08-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0020_remove_fileupload_resource_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='resource_type',
            field=models.CharField(choices=[('textbook', 'Textbook'), ('file', 'File'), ('link', 'Link')], max_length=8),
        ),
    ]
