# Generated by Django 4.2.21 on 2025-08-14 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0022_fileupload_pinned_resource_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='pinned_resource',
            new_name='file_pinned',
        ),
        migrations.RenameField(
            model_name='linkupload',
            old_name='pinned_resource',
            new_name='link_pinned',
        ),
    ]
