# Generated by Django 4.2.21 on 2025-08-14 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solostudyroom', '0001_initial'),
        ('resources', '0023_rename_pinned_resource_fileupload_file_pinned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file_pinned',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='solostudyroom.pinnedresources'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='linkupload',
            name='link_pinned',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='solostudyroom.pinnedresources'),
            preserve_default=False,
        ),
    ]
