# Generated by Django 4.2.21 on 2025-08-16 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0024_alter_fileupload_file_pinned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='file_pinned',
        ),
        migrations.RemoveField(
            model_name='linkupload',
            name='link_pinned',
        ),
    ]
